# Site
repository: meczy/meczy
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Meczy González Jiménez
title: Software Developer
email: meczy.gon@gmail.com
website: 
# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  Meczy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: meczy.g
linkedin_username: meczy-gonzález-jimenéz
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software developer with over four years of experience in web development, specializing in full stack. I am an expert in responsive web development using technologies such as Liferay, Adobe Commerce and .Net, with a focus on Cx discipline.
  I am most skilled in: <mark>Java</mark> and <mark>Eating Pizza</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imagineer Customer Experience
       # link: 
        # link_text: 
        sub_title: Software Developer
        caption: April 2019 - January 2024
       # quote: >
        description: | # this will include new lines to allow paragraphs
            ● Development of responsive websites using Liferay and e-commerce with Adobe Commerce, focusing on the Customer Experience (Cx) discipline.
            ● Maintain and continually update websites.
            ● Use of technologies such as Java, PHP, JavaScript, jQuery, HTML, CSS (Bootstrap) and MySQL, .Net.
            ● Development of custom modules for Adobe Commerce according to customer requirements.
            ● Application of agile methodologies such as Growth-Driven Design and Scrum for effective project management.
            ● Development of plugins for HubSpot, including workflows, offers, customer management and marketing.
            ● Server maintenance tasks on AWS and Windows Server.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Nacional de Costa Rica
        caption: 2019
        sub_title: Information Systems Engineering with a Bachelor's Degree
      #  quote: >
        description: | # this will include new lines to allow paragraphs
          While at the National University, I was involved in the design and development of an entry and exit control system for visitors to the company Coopetrajes del Poás RL, which spanned approximately 18 months from February 2018 to June 2019. The project utilized C# as the programming language, MySQL as the database and the Scrum methodology.

  - title: Skills and Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
    Skills
      - Visual Basic, C, C++, Java, .Net, JavaScript, Python, Swift HTML, CSS, Linux, WordPress, Adobe Commerce.
      - JavaScript, jQuery, TypeScript HTML, HTML5, CSS, CSS3, web programming skills, e-commerce, teamwork, verbal communication, cross-browser compatibility, web UI design, security principles, object-oriented design, API.
      - Configuration, administration and monitoring of Amazon LightSail Servers.

      Certifications
      - HubSpot CMS Developer Certification (HubSpot Academy)
      - Adobe Commerce Business Professional Certification (Adobe)
      - Growth-Driven Design Certification (HubSpot Academy)
      - CMS Hub Implementation (HubSpot Academy)
      - Explore Emerging Tech (IBM)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
