# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Meczy González Jiménez
title: Software Developer
email: meczy.gon@gmail.com
website: 
# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  Meczy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: meczy.g
linkedin_username: meczy-gonzález-jimenéz
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Software developer with over four years of experience in web development, specializing in full stack. I am an expert in responsive web development using technologies such as Liferay, Adobe Commerce and .Net, with a focus on Cx discipline. I am committed to delivering high-quality projects using agile methodologies such as Scrum and GDD. I am proud of my ability to collaborate effectively in multidisciplinary teams. I am passionate about continuing to learn and grow professionally in a dynamic and challenging environment.
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Meczy
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imagineer Costumer Experience
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: April 2019 - January 2024
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            ● Development of responsive websites using Liferay and e-commerce with Adobe Commerce, focusing on the Customer Experience (Cx) discipline.
            ● Maintain and continually update websites.
            ● Use of technologies such as Java, PHP, JavaScript, jQuery, HTML, CSS (Bootstrap) and MySQL, .Net.
            ● Development of custom modules for Adobe Commerce according to customer requirements.
            ● Application of agile methodologies such as Growth-Driven Design and Scrum for effective project management.
            ● Development of plugins for HubSpot, including workflows, offers, customer management and marketing.
            ● Server maintenance tasks on AWS and Windows Server.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Nacional de Costa Rica
        caption: 2019
        sub_title: Information Systems Engineering with a Bachelor's Degree
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          While at the National University, I was involved in the design and development of an entry and exit control system for visitors to the company Coopetrajes del Poás RL, which spanned approximately 18 months from February 2018 to June 2019. The project utilized C# as the programming language, MySQL as the database and the Scrum methodology.

  - title: Skills and Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
    Skills:
      - Visual Basic, C, C++, Java, .Net, JavaScript, Python, Swift HTML, CSS, Linux, WordPress, Adobe Commerce.
      - JavaScript, jQuery, TypeScript HTML, HTML5, CSS, CSS3, web programming skills, e-commerce, teamwork, verbal communication, cross-browser compatibility, web UI design, security principles, object-oriented design, API.
      - Configuration, administration and monitoring of Amazon LightSail Servers.

      Certifications:
      - HubSpot CMS Developer Certification (HubSpot Academy)
      - Adobe Commerce Business Professional Certification (Adobe)
      - Growth-Driven Design Certification (HubSpot Academy)
      - CMS Hub Implementation (HubSpot Academy)
      - Explore Emerging Tech (IBM)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
